num_training_steps: 300_000

data:
  train_path: /home/kunato/mt3/temp_data
  test_path: /home/kunato/mt3/temp_data

event_length: 1024
mel_length: 256
pretrained: pretrained/mt3.pth

lr: 2e-5

per_device_batch_size: 32 # 64
gradient_clip_val: 0
grad_accum: 1
gpus: 0
